 services:
  # GitHub Actions Runner (B-Dev)
  runner:
    image: ghcr.io/actions/actions-runner:latest
    container_name: ${TAG}-client-runner
    entrypoint: /runner/runner-entrypoint.sh
    environment:
      - REPO_URL=https://github.com/LDJ5098/IoT-Security-Architecture-Configure
      - RUNNER_NAME=${TAG}-client-runner
      - ACCESS_TOKEN=${RUNNER_PAT}
      - RUNNER_WORKDIR=/tmp/runner
      - LABELS=client-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner:/runner